FROM jdk8:latest
MAINTAINER baozhichao@ultrapower.com.cn
COPY eureka-server-1.0.jar /
EXPOSE 8080
ENV TZ=Asia/Shanghai
ENV DEBUG=false
ENV EUREKA_HOST localhost
ENV SERVER_PORT 8080
#RUN ln -snf /usr/share/zoneinfo/Asia/Shanghai      /etc/localtime
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENTRYPOINT nohup java -jar /eureka-server-1.0.jar --debug=$DEBUG --eureka.instance.hostname=$EUREKA_HOST --server.port=$SERVER_PORT